spring.application.name=menu

spring.datasource.url=jdbc:postgresql://localhost:5432/menu_db
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

spring.jpa.hibernate.ddl-auto=update