spring.application.name=companyreviews

spring.datasource.url=jdbc:postgresql://localhost:5432/company_reviews
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

spring.jpa.hibernate.ddl-auto=update